version: "3.3"

services:
  frontend:
    build:
      args:
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: local
    ports:
      - 3000:3000
    image: react-professional-hooks
    container_name: react-professional-hooks-proyecto
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
