version: "3.3"

services:
  frontend:
    build:
      args:
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: local
    ports:
      - 8080:8080
    image: custom-docker-node
    container_name: custom-docker-node
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
